module.exports = db => {
  const { 
    A_BusinessPartner,
    A_BusinessPartnerAddress, 
    A_Customer, 
    A_CustomerSalesArea, 
    A_CustomerCompany 
  } = db.entities(
    'API_BUSINESS_PARTNER'
  )

  DELETE.from(A_BusinessPartner+'')
  INSERT.into(A_BusinessPartner).entries(
    {
      "BusinessPartner": "1000021",
      "Customer": "1000021",
      "Supplier": "",
      "AcademicTitle": "",
      "AuthorizationGroup": "",
      "BusinessPartnerCategory": "2",
      "BusinessPartnerFullName": "Bikes Pro Inc.",
      "BusinessPartnerGrouping": "BP02",
      "BusinessPartnerName": "Bikes Pro Inc.",
      "BusinessPartnerUUID": "00163e19-8846-1ed6-a6cf-7b541e621558",
      "CorrespondenceLanguage": "",
      "CreatedByUser": "CB9980000173",
      "FirstName": "",
      "FormOfAddress": "",
      "Industry": "",
      "InternationalLocationNumber1": "0",
      "InternationalLocationNumber2": "0",
      "IsFemale": false,
      "IsMale": false,
      "IsNaturalPerson": "",
      "IsSexUnknown": false,
      "Language": "",
      "LastChangedByUser": "CB9980000173",
      "LastName": "",
      "LegalForm": "",
      "OrganizationBPName1": "Bikes Pro Inc.",
      "OrganizationBPName2": "",
      "OrganizationBPName3": "",
      "OrganizationBPName4": "",
      "OrganizationFoundationDate": null,
      "OrganizationLiquidationDate": null,
      "SearchTerm1": "BIKES",
      "AdditionalLastName": "",
      "BirthDate": null,
      "BusinessPartnerIsBlocked": false,
      "BusinessPartnerType": "",
      "ETag": "CB998000017320161025063117",
      "GroupBusinessPartnerName1": "",
      "GroupBusinessPartnerName2": "",
      "IndependentAddressID": "",
      "InternationalLocationNumber3": "0",
      "MiddleName": "",
      "NameCountry": "",
      "NameFormat": "",
      "PersonFullName": "",
      "PersonNumber": "",
      "IsMarkedForArchiving": false,
      "BusinessPartnerIDByExtSystem": "",
      "TradingPartner": ""
    },
    {
      "BusinessPartner": "1000046",
      "Customer": "1000046",
      "Supplier": "",
      "AcademicTitle": "",
      "AuthorizationGroup": "",
      "BusinessPartnerCategory": "2",
      "BusinessPartnerFullName": "Sound Vision Corp",
      "BusinessPartnerGrouping": "BP02",
      "BusinessPartnerName": "Sound Vision Corp",
      "BusinessPartnerUUID": "00163e19-8846-1ed6-a782-5b9211a01be5",
      "CorrespondenceLanguage": "",
      "CreatedByUser": "S4TESTER",
      "FirstName": "",
      "FormOfAddress": "0003",
      "Industry": "",
      "InternationalLocationNumber1": "0",
      "InternationalLocationNumber2": "0",
      "IsFemale": false,
      "IsMale": false,
      "IsNaturalPerson": "",
      "IsSexUnknown": false,
      "Language": "",
      "LastChangeDate": null,
      "LastChangedByUser": "",
      "LastName": "",
      "LegalForm": "",
      "OrganizationBPName1": "Sound Vision Corp",
      "OrganizationBPName2": "",
      "OrganizationBPName3": "",
      "OrganizationBPName4": "",
      "OrganizationFoundationDate": null,
      "OrganizationLiquidationDate": null,
      "SearchTerm1": "SOUND VISION CORP",
      "AdditionalLastName": "",
      "BirthDate": null,
      "BusinessPartnerIsBlocked": false,
      "BusinessPartnerType": "",
      "ETag": "S4TESTER20161027070507",
      "GroupBusinessPartnerName1": "",
      "GroupBusinessPartnerName2": "",
      "IndependentAddressID": "",
      "InternationalLocationNumber3": "0",
      "MiddleName": "",
      "NameCountry": "",
      "NameFormat": "",
      "PersonFullName": "",
      "PersonNumber": "",
      "IsMarkedForArchiving": false,
      "BusinessPartnerIDByExtSystem": "",
      "TradingPartner": "",
    }
  )

  DELETE.from(A_BusinessPartnerAddress+'')
  INSERT.into(A_BusinessPartnerAddress).entries(
    {
      "BusinessPartner": "1000021",
      "AddressID": "24134",
      "AuthorizationGroup": "",
      "AddressUUID": "00163e19-8846-1ed6-a6cf-93e6eddfb597",
      "AdditionalStreetPrefixName": "",
      "AdditionalStreetSuffixName": "",
      "AddressTimeZone": "PST",
      "CareOfName": "",
      "CityCode": "",
      "CityName": "Palo Alto",
      "CompanyPostalCode": "",
      "Country": "US",
      "County": "",
      "DeliveryServiceNumber": "",
      "DeliveryServiceTypeCode": "",
      "District": "SANTA CLARA",
      "FormOfAddress": "",
      "FullName": "Bikes Pro Inc.",
      "HomeCityName": "",
      "HouseNumber": "",
      "HouseNumberSupplementText": "",
      "Language": "EN",
      "POBox": "",
      "POBoxDeviatingCityName": "",
      "POBoxDeviatingCountry": "",
      "POBoxDeviatingRegion": "",
      "POBoxIsWithoutNumber": false,
      "POBoxLobbyName": "",
      "POBoxPostalCode": "",
      "Person": "",
      "PostalCode": "94304-1355",
      "PrfrdCommMediumType": "",
      "Region": "CA",
      "StreetName": "#B302",
      "StreetPrefixName": "",
      "StreetSuffixName": "",
      "TaxJurisdiction": "0508525200",
      "TransportZone": "",
      "AddressIDByExternalSystem": "",
    },
    {
      "BusinessPartner": "1000046",
      "AddressID": "24183",
      "AuthorizationGroup": "",
      "AddressUUID": "00163e19-8846-1ed6-a782-6b59fc245bed",
      "AdditionalStreetPrefixName": "",
      "AdditionalStreetSuffixName": "",
      "AddressTimeZone": "CET",
      "CareOfName": "",
      "CityCode": "",
      "CityName": "PT",
      "CompanyPostalCode": "",
      "Country": "FR",
      "County": "",
      "DeliveryServiceNumber": "",
      "DeliveryServiceTypeCode": "",
      "District": "",
      "FormOfAddress": "0003",
      "FullName": "Sound Vision Corp",
      "HomeCityName": "",
      "HouseNumber": "",
      "HouseNumberSupplementText": "",
      "Language": "EN",
      "POBox": "",
      "POBoxDeviatingCityName": "",
      "POBoxDeviatingCountry": "",
      "POBoxDeviatingRegion": "",
      "POBoxIsWithoutNumber": false,
      "POBoxLobbyName": "",
      "POBoxPostalCode": "",
      "Person": "",
      "PostalCode": "12344",
      "PrfrdCommMediumType": "",
      "Region": "",
      "StreetName": "",
      "StreetPrefixName": "",
      "StreetSuffixName": "",
      "TaxJurisdiction": "",
      "TransportZone": "",
      "AddressIDByExternalSystem": "",
    }
  )
  DELETE.from(A_Customer+'')
  INSERT.into(A_Customer).entries(
    {
      "Customer": "1000021",
      "AuthorizationGroup": "",
      "BillingIsBlockedForCustomer": "",
      "CreatedByUser": "CB9980000173",
      "CustomerAccountGroup": "CUST",
      "CustomerClassification": "",
      "CustomerFullName": " Bikes Pro Inc./94304-1355 Palo Alto",
      "CustomerName": "Bikes Pro Inc.",
      "DeliveryIsBlocked": "",
      "NFPartnerIsNaturalPerson": "",
      "OrderIsBlockedForCustomer": "",
      "PostingIsBlocked": false,
      "Supplier": "",
      "CustomerCorporateGroup": "",
      "FiscalAddress": "",
      "Industry": "",
      "IndustryCode1": "",
      "IndustryCode2": "",
      "IndustryCode3": "",
      "IndustryCode4": "",
      "IndustryCode5": "",
      "InternationalLocationNumber1": "0",
      "NielsenRegion": "",
      "ResponsibleType": "",
      "TaxNumber1": "",
      "TaxNumber2": "",
      "TaxNumber3": "",
      "TaxNumber4": "",
      "TaxNumber5": "",
      "TaxNumberType": "",
      "VATRegistration": "",
      "DeletionIndicator": false
    },
    {
      "Customer": "1000046",
      "AuthorizationGroup": "",
      "BillingIsBlockedForCustomer": "",
      "CreatedByUser": "S4TESTER",
      "CustomerAccountGroup": "CUST",
      "CustomerClassification": "",
      "CustomerFullName": "Company Sound Vision Corp/12344 PT",
      "CustomerName": "Sound Vision Corp",
      "DeliveryIsBlocked": "",
      "NFPartnerIsNaturalPerson": "",
      "OrderIsBlockedForCustomer": "",
      "PostingIsBlocked": false,
      "Supplier": "",
      "CustomerCorporateGroup": "",
      "FiscalAddress": "",
      "Industry": "",
      "IndustryCode1": "",
      "IndustryCode2": "",
      "IndustryCode3": "",
      "IndustryCode4": "",
      "IndustryCode5": "",
      "InternationalLocationNumber1": "0",
      "NielsenRegion": "",
      "ResponsibleType": "",
      "TaxNumber1": "",
      "TaxNumber2": "",
      "TaxNumber3": "",
      "TaxNumber4": "",
      "TaxNumber5": "",
      "TaxNumberType": "",
      "VATRegistration": "FR12345678912",
      "DeletionIndicator": false
    }
  )
  DELETE.from(A_CustomerSalesArea+'')
  INSERT.into(A_CustomerSalesArea).entries(
    {
      "Customer": "1000021",
      "SalesOrganization": "1710",
      "DistributionChannel": "10",
      "Division": "00",
      "AccountByCustomer": "",
      "AuthorizationGroup": "",
      "BillingIsBlockedForCustomer": "",
      "CompleteDeliveryIsDefined": false,
      "Currency": "USD",
      "CustomerABCClassification": "",
      "CustomerAccountAssignmentGroup": "",
      "CustomerGroup": "",
      "CustomerPaymentTerms": "",
      "CustomerPriceGroup": "",
      "CustomerPricingProcedure": "",
      "DeliveryIsBlockedForCustomer": "",
      "DeliveryPriority": "0",
      "IncotermsClassification": "",
      "IncotermsLocation2": "",
      "IncotermsVersion": "",
      "IncotermsLocation1": "",
      "DeletionIndicator": false,
      "IncotermsTransferLocation": "",
      "InvoiceDate": "",
      "ItemOrderProbabilityInPercent": "100",
      "OrderCombinationIsAllowed": false,
      "OrderIsBlockedForCustomer": "",
      "PartialDeliveryIsAllowed": "",
      "PriceListType": "",
      "SalesGroup": "",
      "SalesOffice": "",
      "ShippingCondition": "",
      "SupplyingPlant": "",
      "SalesDistrict": "",
      "CustomerAccountGroup": "CUST"
    },
    {
      "Customer": "1000046",
      "SalesOrganization": "1710",
      "DistributionChannel": "10",
      "Division": "00",
      "AccountByCustomer": "",
      "AuthorizationGroup": "",
      "BillingIsBlockedForCustomer": "",
      "CompleteDeliveryIsDefined": false,
      "Currency": "EUR",
      "CustomerABCClassification": "",
      "CustomerAccountAssignmentGroup": "",
      "CustomerGroup": "",
      "CustomerPaymentTerms": "",
      "CustomerPriceGroup": "",
      "CustomerPricingProcedure": "",
      "DeliveryIsBlockedForCustomer": "",
      "DeliveryPriority": "0",
      "IncotermsClassification": "",
      "IncotermsLocation2": "",
      "IncotermsVersion": "",
      "IncotermsLocation1": "",
      "DeletionIndicator": false,
      "IncotermsTransferLocation": "",
      "InvoiceDate": "",
      "ItemOrderProbabilityInPercent": "100",
      "OrderCombinationIsAllowed": false,
      "OrderIsBlockedForCustomer": "",
      "PartialDeliveryIsAllowed": "",
      "PriceListType": "",
      "SalesGroup": "",
      "SalesOffice": "",
      "ShippingCondition": "",
      "SupplyingPlant": "",
      "SalesDistrict": "",
      "CustomerAccountGroup": "CUST"
    }
  )
  DELETE.from(A_CustomerCompany+'')
  INSERT.into(A_CustomerCompany).entries(
    {
      "Customer": "1000046",
      "CompanyCode": "1110",
      "APARToleranceGroup": "",
      "AccountByCustomer": "",
      "AccountingClerk": "",
      "AccountingClerkFaxNumber": "",
      "AccountingClerkInternetAddress": "",
      "AccountingClerkPhoneNumber": "",
      "AlternativePayerAccount": "",
      "AuthorizationGroup": "",
      "CollectiveInvoiceVariant": "",
      "CustomerAccountNote": "",
      "CustomerHeadOffice": "",
      "CustomerSupplierClearingIsUsed": false,
      "HouseBank": "",
      "InterestCalculationCode": "",
      "InterestCalculationDate": null,
      "IntrstCalcFrequencyInMonths": "0",
      "IsToBeLocallyProcessed": false,
      "ItemIsToBePaidSeparately": false,
      "LayoutSortingRule": "",
      "PaymentBlockingReason": "",
      "PaymentMethodsList": "",
      "PaymentTerms": "",
      "PaytAdviceIsSentbyEDI": false,
      "PhysicalInventoryBlockInd": false,
      "ReconciliationAccount": "12100000",
      "RecordPaymentHistoryIndicator": false,
      "UserAtCustomer": "",
      "DeletionIndicator": false,
      "CustomerAccountGroup": "CUST"
    }
  )
}